[package]
name = "jito-searcher-client"
version = "0.1.0"
edition = "2021"
description = "Wrapper around the generated gRPC. Adds auth and retry semantics."

[dependencies]
chrono = "0.4.24"
futures = "0.3.28"
futures-util = "0.3.28"
jito-protos = { path = "../jito_protos" }
log = { workspace = true }
rand = "0.8.5"
prost-types = "0.11.8"
serde = { workspace = true }
solana-client = { workspace = true }
solana-metrics = "2.1.0"
solana-sdk = { workspace = true }
solana-transaction-status = "2.1.0"
thiserror = "1.0.38"
tokio = "1.33.0"
tonic = { version = "=0.8.3", features = ["transport", "tls"]}
