[package]
name = "validators"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = { workspace = true }
config = { path = "../config"}
tokio = { workspace = true }
ipgeolocate = "0.3.5"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = {workspace = true}
ahash = "0.8.11"