syntax = "proto3";
package api;
option go_package = "github.com/nextblock/api";

service Api {
  rpc PostSubmitV2(PostSubmitRequest) returns (PostSubmitResponse);

  rpc PostSubmitBatchV2(PostSubmitBatchRequest) returns (PostSubmitResponse);

  rpc Ping(PingRequest) returns (PongResponse);

  rpc GetTipFloor(TipFloorRequest) returns (TipFloorResponse);

  rpc StreamTipFloor(TipFloorStreamRequest) returns (stream TipFloorResponse);
}

message TipFloorRequest {}

message TipFloorStreamRequest {
  string update_frequency = 1; // e.g. "1m", "5m", "10m"
}

message TipStats {
  string time = 1;
  double landed_tips_25th_percentile = 2;
  double landed_tips_50th_percentile = 3;
  double landed_tips_75th_percentile = 4;
  double landed_tips_95th_percentile = 5;
  double landed_tips_99th_percentile = 6;
  double ema_landed_tips_50th_percentile = 7;
}

message TipFloorResponse {
  repeated TipStats stats = 1;
}

// Add these message definitions
message PingRequest {}

message PongResponse {}

message PostSubmitRequest {
  TransactionMessage transaction = 1;
  bool skipPreFlight = 2;
  optional bool frontRunningProtection = 3;
  reserved 4, 6, 7;
  reserved "tip", "useStakedRPCs", "fastBestEffort";
  optional bool experimentalFrontRunningProtection = 8;
  optional bool snipeTransaction = 9;
  optional bool disableRetries = 10;
  optional bool revertOnFail = 11;
}

message PostSubmitRequestEntry {
  TransactionMessage transaction = 1;
}

message PostSubmitBatchRequest {
  repeated PostSubmitRequestEntry entries = 1;
}

message PostSubmitResponse {
  string signature = 1;
}

message TransactionMessage {
  string content = 1;
  bool isCleanup = 2;
}

message TransactionMessageV2 {
  string content = 1;
}
