solana_program::declare_id!("cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG");
mod accounts;
pub use accounts::{PoolAccount, PoolState, QuoteInput, POOL_ACCOUNT_DISCM};
mod typedefs;
pub use typedefs::*;
mod instructions;
pub use instructions::*;
mod activation_dandler;
mod constants;
mod curve;
mod math;
mod quote;
